---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mfkgunhs/public_html/
    - cp frontend/styles/index.css ${DEPLOYPATH}styles/
    - cp frontend/scripts/index.js ${DEPLOYPATH}scripts/
    - cp frontend/index.html $DEPLOYPATH