---
deployment:
  tasks:
    - export BASEPATH=/home/mfkgunhs/public_html/

    - cp frontend/index.html ${BASEPATH}

    - mkdir -p ${BASEPATH}styles/
    - cp frontend/styles/index.css ${BASEPATH}styles/

    - mkdir -p ${BASEPATH}scripts/
    - cp frontend/scripts/index.js ${BASEPATH}scripts/