---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mfkgunhs/public_html/
    - cp frontend/styles/index.css $DEPLOYPATH
    - cp frontend/scripts/index.js $DEPLOYPATH
    - cp frontend/index.html $DEPLOYPATH