---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mfkgunhs/repositories/FullstackMMA_DataHub
    - /bin/cp /frontend/styles/index.css $DEPLOYPATH
    - /bin/cp /frontend/scripts/index.js $DEPLOYPATH