---
deployment:
  tasks:
    - export BASEPATH=/home/mfkgunhs/public_html/

    - cp frontend/index.html ${BASEPATH}

    - mkdir -p ${BASEPATH}styles/
    - cp frontend/styles/index.css ${BASEPATH}styles/

    - mkdir -p ${BASEPATH}scripts/
    - cp frontend/scripts/index.js ${BASEPATH}scripts/

    - cp frontend/images/favicon.ico ${BASEPATH}

    - source /home/mfkgunhs/virtualenv/repositories/FullstackMMA_DataHub/server_API/3.10/bin/activate && cd /home/mfkgunhs/repositories/FullstackMMA_DataHub/server_API
    
    